config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  root 'pages#checkout'

  post 'process-checkout' => 'pages#process_checkout', as: 'process_checkout'
  post 'process-card' => 'pages#process_card', as: 'process_card'
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id               :integer          not null, primary key
#  address_1        :string
#  address_2        :string
#  apartment_number :string
#  city             :string
#  state            :string
#  zip              :string
#  style            :string
#  description      :string
#  request_id       :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class Location < ActiveRecord::Base
  belongs_to :request

  scope :users, -> { where(associated_type: 'User')  }

  STYLES = ['Home', 'Office','Public Place']

end

app/models/request.rb
# == Schema Information
#
# Table name: requests
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  name       :string
#  comment    :text
#  created_at :datetime
#  updated_at :datetime
#

class Request < ActiveRecord::Base
  has_one :location
  accepts_nested_attributes_for :location

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  first_name             :string
#  last_name              :string
#  howd_you_hear          :string
#  mobile_number          :string
#  agree_terms            :boolean
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def landing
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
    flash[:notice] = "this is a dismissable flash notice"
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.

  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:first_name, :last_name, :mobile_number, :howd_you_hear,
                                                      :password, :password_confirmation, :email)}
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class(flash_type)
    { success: 'alert-success',
      error:   'alert-danger',
      alert:   'alert-warning',
      notice:  'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/views/layouts/_application_footer.html.haml
%nav.navbar.navbar-default.navbar-fixed-bottom.footerstyling
  %div.container.row
   
    %div.col-md-8.col-md-offset-3.col-sm-8.col-sm-offset-3.copyright
      © 2015 Company Inc
    %div.col-md-4.col-sm-4.social-media
      = link_to image_tag( 'facebook.svg'), 'http://www.facebook.com'
      = link_to image_tag( 'twitter.svg'), 'http://www.twitter.com'
      = link_to image_tag( 'linkedin.svg'), 'http://www.linkedin.com'
      = link_to image_tag( 'youtube.svg'), 'http://www.youtube.com'

app/views/layouts/_application_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      .navbar-brand= link_to "Brand Logo", root_path

    .collapse.navbar-collapse.navbar-ex1-collapse
      
      %ul.nav.navbar-nav.navbar-right

        - if current_user
          %li= link_to "Log out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign up", new_user_registration_path
          %li= link_to "Sign in", new_user_session_path
      %div.navbar-nav.navbar-right.call-icons
        %button.tutor{:type=>"button"}
          Become a tutor
        = link_to image_tag( 'info.svg'), 'http://www.facebook.com'
        = link_to image_tag( 'phonecall.svg'), 'http://www.facebook.com'
        = link_to image_tag( 'email.svg'), 'http://www.facebook.com'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RegistrationTest
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tags
  %body
    = render 'layouts/application_header'
    = render 'shared/flash'

    = yield
    = render 'layouts/application_footer'
    -# TODO add footer

app/views/pages/checkout.html.haml
-# style this page to match the design file
-# Design file: https://www.dropbox.com/s/zv1ew9qym7ivntk/checkout_shared.ai?dl=0
-# instructions: https://www.evernote.com/l/ACKh4l09QcxMap3B3hygaRVCZmI9VwiQhSc
-# do as much as you can within two hours
-# ignore header and footer for now
-# the more commits the better
-# details matter
-# commenting doesn't hurt either
-# submit a PR when complete

-# hint, do a project wide search for "todo"



.checkout

  .left-pane
    = simple_form_for @request, url: process_checkout_path do |f|

      = f.input :name, label: 'Student\'s name', label_html: {class: 'display-block'}, wrapper_html: {class: 'row col-sm-8'}
      = f.fields_for :location, Location.new do |l|
        .row.col-sm-8
          %label.display-block Location Type
          = l.select :style, Location::STYLES

        .row
          = l.input :address_1, label: 'Address', label_html: {class: 'display-block'}, wrapper_html: {class: 'col-sm-8'}
          = l.input :apartment_number, label: 'Apt # (If Applicable)', label_html: {class: 'display-block'}, wrapper_html: {class: 'col-sm-4'}

        .row
          = l.input :zip, label: 'Zip Code', label_html: {class: 'display-block'}, wrapper_html: {class: 'col-sm-4'}
          .col-sm-8.save-address-box
            %label Save Address
            = f.input_field :save_address, as: :boolean, class: 'initial-width'

      .row
        .col-sm-12
          %label.display-block Special Instructions(Optional)
          = f.text_area :comment, class: 'col-sm-12'


    %hr
    %h4 Payment Information
    %p Please note, you will not be charged until after the session. If you’re unsatisfied with your experience, there’s a money-back guarantee.

    = form_tag process_card_path, method: :post, id: 'payment-form' do
      .row
        .col-sm-8
          %label.display-block Card Number
          = text_field_tag :number, nil, {'data-stripe' => 'number', class: 'form-control'}
      .row
        .col-sm-8
          %label.display-block Expiration
          .col-sm-6
            = select_tag :exp_month, options_for_select(@months, Date.today.month), {'data-stripe' => 'exp_month'}
          .col-sm-6
            = select_tag :exp_year, options_for_select(@next_ten_years), {'data-stripe' => 'exp_year'}
        .col-sm-4
          = label_tag 'CVV'
          = text_field_tag :cvv, nil, {'data-stripe' => 'cvv'}

  .right-pane

    .div Grade #{@grade}

    -# go look at base.js.coffee. The action starts there :)
    .btn.btn-primary.btn-block#checkout Complete Booking

app/views/pages/landing.html.haml
%h1 Registration Test
%hr

%ul
  %li style users/registrators/new.html.haml to match the #{link_to 'Illustrator file', 'http://bit.ly/registrationTest', target: '_blank'}
  %li hint: do a project wide search for "to do". Most of the files are ready for you.
  %li message me with any questions
  %li submit a pull request

- if current_user.present?
  %hr
  = link_to "Log out", destroy_user_session_path, method: :delete

app/views/shared/_flash.haml
- flash.each do |type, message|
  %div{ class: "alert #{bootstrap_flash_class(type)} fade in" }
    = message
    %button.close{ data: { dismiss: 'alert' } } x

app/views/shared/_flash.html.haml
- if flash
  .flash-msg-container
    - flash.each do |name, msg|
      = msg

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/